project:
  type: website

website:
  title: | 
    ![](logo.png){width=50px .nolightbox} &nbsp; Rebecca Senft
  site-url: https://rsenft1.github.io
  description: "This is Rebecca Senft's personal website and blog."
  navbar:
    right:
      - text: Resume
        href: testpage.qmd
      - text: Blog
        href: blog.qmd
      - text: Data viz
        href: data-portfolio.qmd
      - icon: github
        href: https://github.com/rsenft1
      - icon: twitter
        href: https://twitter.com/senftrebecca
      - icon: linkedin
        href: https://www.linkedin.com/in/rebecca-senft/

format:
  html:
    theme:
      light: [united, custom.scss]
      dark: [superhero, custom.scss]
    css: styles.css

editor: visual

